# config/packages/vich_uploader.yaml or app/config/config.yml
vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        utilisateur:
            uri_prefix: /images/utilisateur
            upload_destination: '%kernel.project_dir%/public/images/utilisateur'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer