# config/packages/vich_uploader.yaml or app/config/config.yml
vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        books:
            uri_prefix: /images/books
            upload_destination: '%kernel.project_dir%/public/uploads/books'
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
        utilisateur:
            uri_prefix: /images/utilisateur
            upload_destination: '%kernel.project_dir%/public/images/utilisateur'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer